server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:manifest|appcache|html|xml|json)$ {
    add_header Cache-Control "no-cache";
  }

  location ~* \.(?:css|js|woff2?|ttf|eot|otf|svg|png|jpg|jpeg|gif|ico)$ {
    add_header Cache-Control "public, max-age=31536000, immutable";
  }
}
