// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHLl-5vSwhNSKyXNEfYMwXv6ILTyWzgE0',
    appId: '1:412649761434:web:a8093b9a16ba6f8084cd23',
    messagingSenderId: '412649761434',
    projectId: 'veritask-9092a',
    authDomain: 'veritask-9092a.firebaseapp.com',
    storageBucket: 'veritask-9092a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9hQRfrS1FSBwCBij36FWYmIb-32EOihY',
    appId: '1:412649761434:android:0927dcfdb611c1ff84cd23',
    messagingSenderId: '412649761434',
    projectId: 'veritask-9092a',
    storageBucket: 'veritask-9092a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_P-Tz0fhRR3Inf3y0gbPsGlXg6UB6H-w',
    appId: '1:412649761434:ios:b5bdac11eed2098c84cd23',
    messagingSenderId: '412649761434',
    projectId: 'veritask-9092a',
    storageBucket: 'veritask-9092a.firebasestorage.app',
    iosClientId: '412649761434-pao95udevknr5acg6lp5l27hq3rha282.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanjay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_P-Tz0fhRR3Inf3y0gbPsGlXg6UB6H-w',
    appId: '1:412649761434:ios:b5bdac11eed2098c84cd23',
    messagingSenderId: '412649761434',
    projectId: 'veritask-9092a',
    storageBucket: 'veritask-9092a.firebasestorage.app',
    iosClientId: '412649761434-pao95udevknr5acg6lp5l27hq3rha282.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanjay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHLl-5vSwhNSKyXNEfYMwXv6ILTyWzgE0',
    appId: '1:412649761434:web:25a4bbda17e6539184cd23',
    messagingSenderId: '412649761434',
    projectId: 'veritask-9092a',
    authDomain: 'veritask-9092a.firebaseapp.com',
    storageBucket: 'veritask-9092a.firebasestorage.app',
  );
}
